#
# Module manifest for module 'Find-DhcpServerv4ScopeID'
#
# Generated by: Flemming Sørvollen Skaret
#
# Generated on: 14.08.2019
#

@{

# ID used to uniquely identify this module
GUID = '0ea1ffce-5717-4710-90d8-922855387be4'

# Author of this module
Author = 'Flemming Sørvollen Skaret'

# Copyright statement for this module
Copyright = '(c) 2019 Flemming Sørvollen Skaret.'

# Description of the functionality provided by this module
Description = 'Find the ScopeID Which contains a specific ipv4 address'

# HelpInfo URI of this module
HelpInfoURI = 'https://github.com/flemmingss/Find-DhcpServerv4ScopeID'

}

